### ISSUE TITLE
not enough LFS bandwidth

### ISSUE THREAD

**Issue by fishjojo** [pyscf/pyscf-build-deps#1]
I guess each time the ci workflow downloads the deps files, it consumes the bandwidth (https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage).
And we only have 1Gb free bandwidth per month... And the ci workflow will fail downloading the deps files once the bandwidth is used up.

**Comment by sunqm** [comment]
Data package plan upgraded
